language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install coveralls
  - pip3 install -r requirements.txt
# command to run tests
script:
  - coverage run --source fantasyasst -m unittest discover --start-directory test
after_success:
  - coveralls